### ISSUE TITLE
NoInterfaceObject missing or in wrong path

### ISSUE THREAD

**Issue by jmajnert** [w3c/packaged-webapps#1]
The NoInterfaceObject.wgt file is missing from the api test suite (or it is in location other than that stated in tests.xml)

**Comment by marcoscaceres** [comment]
@jmajnert I'm away on vacation for the next month. It might still be on the W3C server. I think there is a link from the spec itself to the test suite... w3c server doesn't seem to be responding right now :(

**Comment by jmajnert** [comment]
No problem. Just wanted to make you aware of this

**Comment by jmajnert** [comment]
Is this still relevant?
