### ISSUE TITLE
x180E no longer a Unicode whitespace

### ISSUE THREAD

**Issue by jmajnert** [w3c/packaged-webapps#2]
Please take a look at this bug in Crosswalk project:
https://crosswalk-project.org/jira/browse/XWALK-2982

It looks like since W3C P&C became a standard, unicode got rid of x180E whitespace (this is no longer a MONGOLIAN VOWEL SEPARATOR).

Should the test cases be updated to reflect this? I think this only affects as.wgt.

**Comment by jmajnert** [comment]
https://github.com/w3c/packaged-webapps/pull/3  fixes this issue

**Comment by jmajnert** [comment]
This affects these files:
test-cases/ta-AYLMhryBnD/004/config.xml:
test-cases/ta-AYLMhryBnD/002/config.xml
test-cases/ta-AYLMhryBnD/001/config.xml
test-cases/ta-argMozRiC/004/config.xml
test-cases/ta-argMozRiC/002/config.xml
test-cases/ta-argMozRiC/001/config.xml

**Comment by jmajnert** [comment]
Just noticed that the specification text also mentions the 180E codepoint as a whitespace char...

**Comment by marcoscaceres** [comment]
I added this change to the errata for PnC.

**Comment by jmajnert** [comment]
LGTM
